In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

print("SQL Analysis notebook started successfully!")

SQL Analysis notebook started successfully!

In [2]:
username = "root"
password = "Srivani@123"

connection_url = URL.create(
    drivername="mysql+pymysql",
    username=username,
    password=password,
    host="localhost",
    port=3306,
    database="methanol_project"
)

engine = create_engine(connection_url)

with engine.connect() as connection:
    print("Connected database:", connection.execute(
        text("SELECT DATABASE()")
    ).scalar())

Connected database: methanol_project

In [3]:
query = """
SELECT COUNT(*) AS Total_Records
FROM equilibrium_results;
"""

record_count = pd.read_sql(text(query), engine)
display(record_count)

   Total_Records
0             20

In [4]:
query = """
SELECT
    Temperature_K,
    Pressure_bar,
    CO2_Conversion_pct,
    Methanol_Yield_pct
FROM equilibrium_results
ORDER BY Methanol_Yield_pct DESC
LIMIT 10;
"""

top_conditions = pd.read_sql(text(query), engine)
display(top_conditions.round(3))

   Temperature_K  Pressure_bar  CO2_Conversion_pct  Methanol_Yield_pct
0          400.0          70.0              62.872              62.829
1          400.0          50.0              57.239              57.177
2          400.0          30.0              47.900              47.789
3          450.0          70.0              46.731              46.273
4          450.0          50.0              40.362              39.695
5          500.0          70.0              33.423              30.434
6          450.0          30.0              31.026              29.862
7          400.0          10.0              27.475              27.102
8          500.0          50.0              28.095              23.912
9          550.0          70.0              26.996              15.665

In [5]:
query = """
SELECT
    Pressure_bar,
    ROUND(AVG(Methanol_Yield_pct), 2) AS Avg_Methanol_Yield
FROM equilibrium_results
GROUP BY Pressure_bar
ORDER BY Pressure_bar;
"""

pressure_analysis = pd.read_sql(text(query), engine)
display(pressure_analysis)

   Pressure_bar  Avg_Methanol_Yield
0          10.0                8.71
1          30.0               19.72
2          50.0               26.82
3          70.0               32.12

In [6]:
query = """
SELECT
    Temperature_K,
    ROUND(AVG(Methanol_Yield_pct), 2) AS Avg_Methanol_Yield
FROM equilibrium_results
GROUP BY Temperature_K
ORDER BY Temperature_K;
"""

temperature_analysis = pd.read_sql(text(query), engine)
display(temperature_analysis)

   Temperature_K  Avg_Methanol_Yield
0          400.0               48.72
1          450.0               32.06
2          500.0               18.17
3          550.0                7.83
4          600.0                2.43

In [7]:
query = """
SELECT
    Temperature_K,
    Pressure_bar,
    ROUND(Methanol_Yield_pct, 2) AS Methanol_Yield_pct
FROM equilibrium_results
ORDER BY Temperature_K, Pressure_bar;
"""

yield_comparison = pd.read_sql(text(query), engine)
display(yield_comparison)

    Temperature_K  Pressure_bar  Methanol_Yield_pct
0           400.0          10.0               27.10
1           400.0          30.0               47.79
2           400.0          50.0               57.18
3           400.0          70.0               62.83
4           450.0          10.0               12.41
5           450.0          30.0               29.86
6           450.0          50.0               39.70
7           450.0          70.0               46.27
8           500.0          10.0                3.29
9           500.0          30.0               15.04
10          500.0          50.0               23.91
11          500.0          70.0               30.43
12          550.0          10.0                0.62
13          550.0          30.0                4.73
14          550.0          50.0               10.31
15          550.0          70.0               15.67
16          600.0          10.0                0.13
17          600.0          30.0                1.15
18          600.0          50.0                3.01
19          600.0          70.0                5.42

In [8]:
query = """
SELECT
    Temperature_K,
    Pressure_bar,
    CO2_Conversion_pct,
    Methanol_Yield_pct,
    Methanol_mol
FROM equilibrium_results
ORDER BY Methanol_Yield_pct DESC
LIMIT 1;
"""

best_condition = pd.read_sql(text(query), engine)
display(best_condition.round(3))

,Temperature_K,Pressure_bar,CO2_Conversion_pct,Methanol_Yield_pct,Methanol_mol
0,400.0,70.0,62.872,62.829,0.628

In [9]:
query = """
SELECT
    Solver_success,
    COUNT(*) AS Number_of_Cases
FROM equilibrium_results
GROUP BY Solver_success;
"""

solver_check = pd.read_sql(text(query), engine)
display(solver_check)

   Solver_success  Number_of_Cases
0               1               20

In [10]:
query = """
SELECT
    Solver_success,
    COUNT(*) AS Number_of_Cases
FROM equilibrium_results
GROUP BY Solver_success
ORDER BY Solver_success;
"""

solver_check = pd.read_sql(text(query), engine)
print(solver_check.to_string(index=False))

 Solver_success  Number_of_Cases
              1               20

In [11]:
query = """
SELECT
    COUNT(*) AS Total_Cases,
    ROUND(AVG(CO2_Conversion_pct), 2) AS Avg_CO2_Conversion_pct,
    ROUND(MAX(CO2_Conversion_pct), 2) AS Max_CO2_Conversion_pct,
    ROUND(AVG(Methanol_Yield_pct), 2) AS Avg_Methanol_Yield_pct,
    ROUND(MAX(Methanol_Yield_pct), 2) AS Max_Methanol_Yield_pct
FROM equilibrium_results
WHERE Solver_success = 1;
"""

performance_summary = pd.read_sql(text(query), engine)
display(performance_summary)

,Total_Cases,Avg_CO2_Conversion_pct,Max_CO2_Conversion_pct,Avg_Methanol_Yield_pct,Max_Methanol_Yield_pct
0,20,31.51,62.87,21.84,62.83

In [12]:
query = """
SELECT
    Pressure_bar,
    ROUND(AVG(Methanol_Yield_pct), 2) AS Avg_Yield_pct,
    ROUND(MAX(Methanol_Yield_pct), 2) AS Max_Yield_pct
FROM equilibrium_results
WHERE Solver_success = 1
GROUP BY Pressure_bar
ORDER BY Avg_Yield_pct DESC;
"""

pressure_ranking = pd.read_sql(text(query), engine)
display(pressure_ranking)

   Pressure_bar  Avg_Yield_pct  Max_Yield_pct
0          70.0          32.12          62.83
1          50.0          26.82          57.18
2          30.0          19.72          47.79
3          10.0           8.71          27.10

In [13]:
query = """
SELECT
    Temperature_K,
    ROUND(AVG(Methanol_Yield_pct), 2) AS Avg_Yield_pct,
    ROUND(MAX(Methanol_Yield_pct), 2) AS Max_Yield_pct
FROM equilibrium_results
WHERE Solver_success = 1
GROUP BY Temperature_K
ORDER BY Avg_Yield_pct DESC;
"""

temperature_ranking = pd.read_sql(text(query), engine)
display(temperature_ranking)

   Temperature_K  Avg_Yield_pct  Max_Yield_pct
0          400.0          48.72          62.83
1          450.0          32.06          46.27
2          500.0          18.17          30.43
3          550.0           7.83          15.67
4          600.0           2.43           5.42

In [14]:
query = """
SELECT
    Temperature_K,
    Pressure_bar,
    ROUND(Methanol_Yield_pct, 2) AS Methanol_Yield_pct
FROM equilibrium_results
WHERE Solver_success = 1
ORDER BY Temperature_K, Pressure_bar;
"""

yield_data = pd.read_sql(text(query), engine)

yield_matrix = yield_data.pivot(
    index="Temperature_K",
    columns="Pressure_bar",
    values="Methanol_Yield_pct"
)

display(yield_matrix)

Pressure_bar    10.0   30.0   50.0   70.0
Temperature_K
400.0          27.10  47.79  57.18  62.83
450.0          12.41  29.86  39.70  46.27
500.0           3.29  15.04  23.91  30.43
550.0           0.62   4.73  10.31  15.67
600.0           0.13   1.15   3.01   5.42

In [15]:
yield_data.to_csv("methanol_yield_analysis.csv", index=False)
yield_matrix.to_csv("methanol_yield_matrix.csv")

print("Analysis files exported successfully!")

Analysis files exported successfully!

In [16]:
query = """
SELECT
    COUNT(*) AS Total_Cases,
    ROUND(AVG(CO2_Conversion_pct), 2) AS Average_Conversion_pct,
    ROUND(MAX(CO2_Conversion_pct), 2) AS Maximum_Conversion_pct,
    ROUND(AVG(Methanol_Yield_pct), 2) AS Average_Yield_pct,
    ROUND(MAX(Methanol_Yield_pct), 2) AS Maximum_Yield_pct
FROM equilibrium_results
WHERE Solver_success = 1;
"""

final_summary = pd.read_sql(text(query), engine)
display(final_summary)

,Total_Cases,Average_Conversion_pct,Maximum_Conversion_pct,Average_Yield_pct,Maximum_Yield_pct
0,20,31.51,62.87,21.84,62.83

In [18]:
from pathlib import Path
import shutil

project_folder = Path.home() / "Desktop" / "Chemical_Process_Intelligence"

source = Path.home() / "AppData" / "Local" / "Programs" / "Microsoft VS Code" / "methanol_equilibrium_results.csv"

shutil.copy2(
    source,
    project_folder / "methanol_equilibrium_results.csv"
)

print("Equilibrium results CSV copied successfully!")

Equilibrium results CSV copied successfully!

In [19]:
source = Path.home() / "AppData" / "Local" / "Programs" / "Microsoft VS Code" / "methanol_equilibrium_summary.csv"

if source.exists():
    shutil.copy2(source, project_folder / source.name)
    print("Summary CSV copied successfully!")
else:
    print("Summary CSV not found at the source location.")

Summary CSV copied successfully!

In [20]:
from pathlib import Path
import pandas as pd

project_folder = Path.home() / "Desktop" / "Chemical_Process_Intelligence"
csv_file = project_folder / "methanol_equilibrium_results.csv"

if csv_file.exists():
    df = pd.read_csv(csv_file)
    print("File found:", csv_file.name)
    print("Number of rows:", len(df))
    display(df.head())
else:
    print("CSV file not found in the project folder.")

File found: methanol_equilibrium_results.csv
Number of rows: 20

,Temperature_K,Pressure_bar,CO2_Conversion_pct,Methanol_Yield_pct,Methanol_mol,CO_mol,Solver_success
0,400,10,27.475199,27.101966,0.271020,0.003732,True
1,400,30,47.899683,47.789422,0.477894,0.001103,True
2,400,50,57.238920,57.176792,0.571768,0.000621,True
3,400,70,62.871529,62.828896,0.628289,0.000426,True
4,450,10,15.850807,12.407238,0.124072,0.034436,True

In [21]:
from pathlib import Path

project_folder = Path.home() / "Desktop" / "Chemical_Process_Intelligence"

for file in sorted(project_folder.glob("*.csv")):
    print(file.name)

methanol_equilibrium_results.csv
methanol_equilibrium_summary.csv